shipshapecode/shepherd

package.json

I'm installing shepherd with NPM by listing it as a dependency in my package.json
```
"dependencies": {
"shepherd": "git://github.com/HubSpot/shepherd.git#58a37fa0263bf205fff7a64abb62216b1738e0c2",
},
```
Webpack and Browserify would require the main js file to be listed in the `main` property, instead it is listed in `spm.main`. I'm not using `spm`
For now I've decided to keep both, to not break `spm` support.

Add js file to main property

---

docs/1-Examples/1-projects_using_shepherd.md

Adds __Projects using Shepherd__ section to documentation and adds [ember-shepherd](https://github.com/shipshapecode/ember-shepherd) to section.
Closes #101 
\cc @rwwagner90

Add ember-shepherd to docs

---

src/js/shepherd.js

This change prevents accidental encoding conversion errors of the cancel icon.

Change UTF-8 Character to escaped Unicode

---

README.md

This old link was most likely the cause for https://github.com/shipshapecode/shepherd/issues/185
@rwwagner90 This just uses the link you mention in that issue in the `README.md`

Link correct demo site

---

index.md
src/js/shepherd.js

Add renderLocation option

---

.gitignore
.travis.yml
gulpfile.js
package.json
test/test.tour.js
yarn.lock

This branch adds Mocha for testing and some basic Tour instance tests.

Basic testing framework

---

src/js/evented.js
test/test.evented.js
test/test.step.js
test/test.tour.js
test/test.utils.js

this branch adds some tests for the base class and increases code coverage
```
TOTAL: 21 SUCCESS
-------------|----------|----------|----------|----------|-------------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------|----------|----------|----------|----------|-------------------|
All files    |    72.01 |    59.19 |       64 |    72.78 |                   |
evented.js  |    84.85 |    80.77 |      100 |    84.85 |    30,31,32,33,35 |
shepherd.js |      100 |      100 |      100 |      100 |                   |
step.js     |    66.67 |    55.12 |       40 |    68.02 |... 84,385,400,401 |
tour.js     |    73.81 |       50 |      100 |    73.49 |... 61,165,166,167 |
utils.js    |    90.48 |     87.5 |      100 |    90.48 | …
```

Testing for Evented module

---

.eslintrc.js
src/js/step.js
test/integration/test.shepherd.js

This fix issue in adding cancel link to header that doesn't exist in the DOM yet and increase complexity threshold.

[Bug] - fix issue with cancel button

---

test/unit/test.step.js

```bash
-------------|----------|----------|----------|----------|-------------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------|----------|----------|----------|----------|-------------------|
All files    |      100 |     96.2 |      100 |      100 |                   |
bind.js     |      100 |    83.33 |      100 |      100 |          10,13,47 |
evented.js  |      100 |      100 |      100 |      100 |                   |
shepherd.js |      100 |      100 |      100 |      100 |                   |
step.js     |      100 |    97.26 |      100 |      100 |           121,239 |
tour.js     |      100 |    95.56 |      100 |      100 |            89,185 |
utils.js    |      100 |      100 |      100 |      100 |                   | …
```

add more tests for increased coverage

---

src/js/step.js
webpack.config.js

I was testing with release **2.0.0-beta-24 in IE** and some errors occurred. [Issue 238](https://github.com/shipshapecode/shepherd/issues/238)
Basically putting the `babel/env` back in the webpack config seem make IE load the lib instead of giving us the awful `Syntax Errors` message.
Also, [ParentNode.prepend](https://developer.mozilla.org/fr/docs/Web/API/ParentNode/append) is not fully supported by all the browsers, so it's probably better not to use it since it doesn't seem to be needed in this case.
Cheers!
Resolves #238

Syntax errors and ParentNode.prepend not supported in IE

---

README.md
docs/welcome/index.html
docs/welcome/js/welcome.js
index.md
package.json
src/js/tour.js
test/cypress/integration/test.acceptance.js
test/cypress/utils/setup-tour.js
test/dummy/index.html
test/unit/test.step.js
test/unit/test.tour.js

Closes [#240](https://github.com/shipshapecode/shepherd/issues/240).

Rename `Tour.options.defaults` to `Tour.options.defaultStepOptions`.

---

src/js/step.js
src/js/tour.js
test/unit/test.tour.js

Closes [#249](https://github.com/shipshapecode/shepherd/issues/249).

Implement `Tour.hide`

---

src/js/utils.js

This removes the arrow: true setting if we `_makeCenteredTippy()` since it's not attached to an element that an arrow could point to.

Remove default arrow setting on centered tippy

---

src/js/bind.js
src/js/step.js
src/js/tour.js
src/js/utils/tooltip-defaults.js
test/cypress/integration/element-targeting.spec.js
test/cypress/integration/test.acceptance.js
test/unit/test.step.js
test/unit/test.tour.js

Closes https://github.com/shipshapecode/shepherd/issues/277
This removes our own manual management of `this.el`'s appearance/presence
in the DOM -- since tippy is handling it already. 
This allows the tooltip's exit animation to play, as opposed to having the element disappear instantly before we even call `tippy.hide`.

Allow exit animations to play before step tooltip disappears.

---

test/cypress/integration/element-targeting.spec.js
test/cypress/integration/test.acceptance.js
test/dummy/index.html

Use data attributes for test selectors

---

src/js/tour.js
src/js/utils/cleanup.js
src/js/utils/dom.js
src/js/utils/modal.js

This branch stops the ability on iOS (where overflow: hidden doesn't work) to pull the overlay window out of place and move the mask highlight out of place.
🚈

Fix: stop ontouchstart events on overlay

---

src/js/tour.js
test/cypress/integration/modal.spec.js

this branch adds a call to the `._hideModalOverlay()` when the main tour hide method is called so that the `.shepherd-modal-is-visible` class is removed and pointer events are restored.

fix: remove class when modal hidden so elements are clickable

---

src/js/utils/dom.js

This branch adds the false passive option which is now turned on by default, not allow for preventDefault() calls in listener callbacks.
https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html

fix: turn off passive events for touchmove on Safari > 10

---

src/js/modal.js
src/js/step.js
src/js/tour.js
src/js/utils/cleanup.js
test/unit/run.js
test/unit/test.dom.js
test/unit/test.step.js

I still need to write some tests, now that this is its own class, but wanted to get some eyes on it beforehand.

Move modal to its own class

---

src/scss/_modal-overlay.scss

Added `*` selector as well, to ensure children of things are allowed to be clicked too.
Fixes #328

Fix inability to click things in shepherd-element

---

src/js/utils/modal.js

[Yandex browser](https://en.wikipedia.org/wiki/Yandex_Browser) not support getBoundingClientRect().x.

svg mask for the opening in browsers do not support getBoundingClientRect().x|y

---

src/js/step.js

Added tabindex="0" to shepherd-button to fix the following:
- bootstrap 4 styling needs a href or tabindex to work properly (otherwise some colors aren't correctly applied) (see: https://github.com/twbs/bootstrap/blob/bc60a22a1843928814099ef5e6e26552f55aebae/dist/css/bootstrap.css#L166) 
- https://stackoverflow.com/a/10510353 (adding the role would be optional and scope of another pr?)

Add tabindex="0" to shepherd-button

---

src/js/tour.js

The _modalOverlayElem is destroyed upon cleanup, but is never rebuilt when restarting a tour.
Moved the creation of the modal from the constructor to the startup process of the tour. This way the modal is rebuilt for each run through the tour.
This is a fix for Issue #347

[BugFix] Issue #347

---

src/js/modal.js
src/js/utils/modal.js

Relating to: https://github.com/shipshapecode/shepherd/issues/379

Optional padding on modalOverlayOpening

---

src/js/tour.js

I am not 100% sure if removing this is okay or not. @chuckcarpenter do you know why we had this call here? Is `addStepEventListeners` only necessary when using modal mode?
Fixes #393

Remove addStepEventListeners call

---

docs/welcome/index.html
docs/welcome/js/welcome.js
package.json
src/js/step.js
yarn.lock

This should enable users to pass options like `scrollTo: { behavior: 'smooth', block: 'center' },` which will change the scrolling behavior to center the object and to scroll smoothly. These options come from https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
The `behavior` option is not supported in Safari or IE, so we added a polyfill for them.
Closes #398
Closes #401

Add scrollIntoView options and polyfill

---

package.json
src/types/evented.d.ts
src/types/shepherd.d.ts
src/types/step.d.ts
src/types/tour.d.ts

Trying to implement #359.
For now, only Step types are present as of a base. A couple of things would need to be clarified. 
Many TODOs are in the code @rwwagner90 if you have some time, could you give me your thoughts on this start? There are some things I'm not sure about, if you could check the TODOs that would be nice.
If you like how it goes, I would continue with the other files.

Add TypeScript definitions

---

docs/welcome/css/welcome.css
src/js/step.js
src/scss/_base.scss
src/scss/mixins/_shepherd-button.scss
test/dummy/css/welcome.css
test/unit/step.spec.js

This removes the `shepherd-buttons` wrapper, which I think is no longer really needed. However, we may need to consider this a breaking change, if people have custom styles that rely on the `ul`, `li` stuff.
This was also requested as better for a11y in #198

Remove ul, li button wrapper

---

cypress.json
package.json
src/js/step.js
test/cypress/integration/a11y.spec.js
test/cypress/plugins/index.js
test/cypress/support/commands.js
test/cypress/support/index.js
test/cypress/utils/default-steps.js
test/unit/step.spec.js
yarn.lock

This keyboard trap implementation was taken from https://bitsofco.de/accessible-modal-dialog/ and is related to #198

Add focus trap, to disallow tabbing outside the modal

---

src/js/step.js
test/unit/step.spec.js

Add aria-describedby and aria-labeledby

---

README.md
docs/welcome/index.html
docs/welcome/js/welcome.js
index.md
src/eager/installHelper.js
src/js/step.js
src/js/utils/general.js
test/cypress/integration/modal.spec.js
test/cypress/utils/default-steps.js
test/dummy/index.html
test/unit/step.spec.js
test/unit/utils/cleanup.spec.js
test/unit/utils/dom.spec.js
test/unit/utils/general.spec.js

This will be a breaking change for anyone using the string format, but we wanted to start enforcing one and only one API for each thing, to both remove confusion, and lessen the burden of maintaining several formats.

Remove string option for `attachTo` in favor of object

---

docs/welcome/js/welcome.js
index.md
src/js/step.js
test/cypress/integration/test.acceptance.js
test/cypress/utils/default-steps.js
test/unit/step.spec.js

The array option wrapped each string in a `<p>`, but you can wrap them yourself, by using an HTML string, so it seemed redundant and confusing.

Remove array support for `step.options.text`

---

package.json

incorrect path to types file results in no intellisense or typing support
Fixes #435

fix for incorrect types path in package.json

---

babel.config.js
package.json
src/js/evented.js
src/js/utils/general.js
test/unit/evented.spec.js
test/unit/tour.spec.js
yarn.lock

I think this is redundant, as we can call `slice` directly.

Remove drop util

---

package.json
src/js/step.js
src/js/tour.js
src/js/utils/bind.js
src/js/utils/general.js
test/unit/step.spec.js
test/unit/utils/bind.spec.js
test/unit/utils/general.spec.js
yarn.lock

This is *technically* a breaking change because we were adding some of these utils onto `Step` and `Tour` previously. They were not documented as public API, but since people could have technically called them this is a breaking change.

Use autoBind, pass context rather than manually binding

---

demo/js/welcome.js
src/js/step.js
src/js/styles/generateStyles.js
src/js/styles/nano.js
src/js/tour.js
src/js/utils/bind.js
src/js/utils/general.js

@rwwagner90 This pull request contains some fixes related to prefixes.
There are a few more things to fix, which I'll do in separate pull requests (or maybe you will beat me to it):
* modal classes are not prefixed.
* fix removing 'shepherd-modal-target' class from target when moving on to next (at the moment it remains on all previous steps). Maybe the issue [here](https://github.com/shipshapecode/shepherd/blob/master/src/js/utils/modal.js#L177)

Prefixes fixes

---

demo/index.html
demo/js/welcome.js
docs-src/tutorials/02-usage.md
src/js/step.jsx
src/js/tour.jsx
src/types/tour.d.ts
test/cypress/utils/default-steps.js
test/cypress/utils/setup-tour.js
test/dummy/index.html
test/unit/step.spec.js
test/unit/tour.spec.js

Our addStep logic was hacky and supported a varying number of arguments. Now it takes only one argument, either a hash of the step options or an existing Step object.

Simplify addStep API

---

docs-src/tutorials/02-usage.md
src/js/step.jsx

Document canClickTarget

---

src/js/utils/general.js

tippy options are already applied at: https://github.com/shipshapecode/shepherd/blob/master/src/js/utils/general.js#L179
the deleted lines essentially do something like: 
```
Object.assign({a: 'hello', b: 'bye'}, '400px')
```
which results in:
```
{0: "4", 1: "0", 2: "0", 3: "p", 4: "x", a: "hello", b: "bye"}
```
getVariables import not used (there is error at compile time)

fix applying tippyOptions

---

src/js/components/shepherd-content/shepherd-header/styles.js

when dark color is used for header for example: `shepherdHeaderBackground: 'rgb(20,20,20)'` the cancel link color is broken:
* when there is no title, the 'x' cancel link is white and not visible at all.
* when there is title the 'x' cancel link is white and there is no transparency at all and no hover effect.
This fix, fixes it without breaking light header backgrounds.

fix cancel link color for when the header has dark background

---

src/js/components/shepherd-content/styles.js

at the moment `shepherdElementBorderRadius` has no effect on when `attachTo` is used. It works only for modal.
Because the radius is applied only to header and footer. applying it on content as well, fixes it.

fix content border radius

---

src/js/tour.jsx

We don't always want to append to modal to the body, in some cases we need it to be child of other container element. (for steps we have appendTo tippy option).

Add option to specify container element for the modal

---

src/js/tour.jsx
src/types/step.d.ts
src/types/tour.d.ts

Fix some types and docs

---

demo/js/welcome.js
docs-src/tutorials/02-usage.md
src/js/components/shepherd-content/shepherd-footer/index.jsx
src/js/components/shepherd-content/shepherd-footer/shepherd-button/index.jsx
src/js/step.jsx
src/js/tour.jsx
src/types/step.d.ts
src/types/tour.d.ts
test/cypress/integration/modal.spec.js
test/cypress/integration/test.acceptance.js
test/cypress/utils/default-steps.js
test/cypress/utils/setup-tour.js
yarn.lock

Add addSteps method and allow passing steps to tour constructor

---

src/types/step.d.ts

Simple fix for the wrong type definition of StepOptions.scrollTo property
Fixes #490

Fix for the wrong type definition of StepOptions.scrollTo

---

docs-src/tutorials/02-usage.md
src/js/shepherd.js
yarn.lock

We no longer see a need to expose `Shepherd.Evented`. The events on tours and steps will continue to work. Since this was technically public API, this is a breaking change.

Remove Shepherd.Evented

---

docs-src/tutorials/02-usage.md
src/js/components/shepherd-element/index.jsx
src/js/tour.jsx
src/types/tour.d.ts
test/unit/components/shepherd-element.spec.js

This allows for configurability to disabled keyboard navigation and/or exiting the tour on ESC.
Closes #491

Add keyboardNav and exitOnEsc options

---

demo/css/welcome.css
src/js/components/shepherd-content/shepherd-text/styles.js

We had some opinionated link styles that didn't belong in the framework, so we removed them.

Remove link styles

---

docs-src/tutorials/03-styling.md
src/js/components/shepherd-modal/styles.js
src/js/styles/generateStyles.js
src/js/styles/variables.js

This will allow for setting the opacity of the overlay, more easily, rather than defaulting to 0.5.

Add overlayOpacity to styleVariables options

---

.eslintrc.js
package.json
rollup.config.js
src/js/utils/general.js
src/js/utils/tippy-popper-options.js
test/unit/utils/bind.spec.js
test/unit/utils/tippy-popper-options.spec.js
yarn.lock

Following https://github.com/shipshapecode/shepherd/pull/488
using 1K object-assign-deep seems overkill.
especially since their readme starts with: "Caution! Danger of Death!"
It introduces unnecessary risk fo user error.

Remove object-assign-deep, refactor setting popper options

---

demo/index.html
demo/js/welcome.js
docs-src/tutorials/02-usage.md
src/js/components/shepherd-content/shepherd-header/index.jsx
src/js/components/shepherd-content/shepherd-header/styles.js
src/js/step.jsx
src/js/styles/generateStyles.js
src/types/step.d.ts
test/cypress/integration/test.acceptance.js
test/cypress/utils/setup-tour.js
test/unit/components/shepherd-header.spec.js

This change allows us to pass multiple options for cancelIcon, so we can do things like set the label.
Closes #499

showCancelLink -> cancelIcon

---

src/js/styles/nano.js

We do not seem to need any prefixing of our styles, as everything still works fine in IE. Removing it saves us ~3 kb min + gzip.
This is technically a breaking change, since someone could have been relying on vendor prefixing somewhere.

Remove style vendor prefixing

---

docs-src/tutorials/02-usage.md
src/js/components/shepherd-content/shepherd-footer/shepherd-button/styles.js
src/js/components/shepherd-content/shepherd-footer/styles.js
src/js/components/shepherd-content/shepherd-header/styles.js
src/js/components/shepherd-content/shepherd-text/styles.js
src/js/components/shepherd-content/styles.js
src/js/styles/generateStyles.js
src/js/tour.jsx
src/types/step.d.ts
src/types/tour.d.ts

This will allow users who find themselves overriding a lot of styles to opt out of our base styles. Closes #497

Add includeStyles option

---

src/js/components/shepherd-element/index.jsx

The issue:
if a step contains only 1 focusable element clicking on TAB does not focus on it, the focus stays on the step element.
This fix will focus on the first element and keep the focus on it for subsequent tabs.
If I'm not mistaken, to add cypress a11 test for it, we need to change the welcome tour, since there is no step with single focusable element. Not sure you want to do it, so leave it to you.
[The second commit](https://github.com/shipshapecode/shepherd/pull/532/commits/7479441b0e8f2d4b326d6448430795de19cbbb37) handles another related issue: If there are no focusable elements, pressing TAB will move the focus outside of the tour.
I'm guessing we want to keep it inside. @rwwagner90  What do you think?

Fix tab focus when there are no focusable elements

---

docs-src/tutorials/04-cookbook.md
docs-src/tutorials/config.json
package.json
src/js/tour.jsx
src/types/tour.d.ts
yarn.lock

disableScroll was buggy, and bulky, so removing in favor of users adding body-scroll-lock, or something similar directly in their apps. Added a cookbook entry to mention what to do.

Remove `disableScroll` option

---

README.md
babel.config.js
demo/index.html
package.json
src/js/shepherd.js
src/js/step.jsx
src/js/styles/nano.js
yarn.lock

It is likely if you are supporting IE11, you are already shipping a bunch of polyfills. Rather than supporting IE11 out of the box, we have removed the polyfills and listed which polyfills are necessary to get IE11 working again.

Remove IE11 polyfills, in favor of apps including them

---

src/js/components/shepherd-modal.svelte
src/js/step.js
src/js/tour.js
src/js/utils/general.js
test/unit/step.spec.js

Closes #550 
@chuckcarpenter do you foresee any issues with replacing the old `step-1`, `step-2` style ids with uuid? The thought here is we can reduce code, and use uuid for all ids, as well as guarantee ids are unique.

Replace uniqueId with uuid

---

src/js/components/shepherd-modal.svelte
test/unit/components/shepherd-modal.spec.js

Fixes #585. 
Example after applying the fix:

Adjust modal opening according to scrollParent

---

src/js/components/shepherd-modal.svelte
test/unit/components/shepherd-modal.spec.js

Resolves #585, fixes issue from #589 where elements without scroll parent were clipped when they exceeded the height of the body.

Handle modal opening for targets inside scrollable area

---

README.md

Originally released in 2016, [abraham](https://github.com/actmd/abraham) is a Rails engine that generates Shepherd tours and tracks whether users have completed them. Today, the abraham v2 release offers Shepherd v6 support.
(Thanks for keeping Shepherd going, the Rails community appreciates it!)

Add abraham project to README

---

CONTRIBUTING.md

I removed some commas that were syntactically placed as parenthetical commas despite the contained information not actually being parenthetical.

Removed unnecessary parenthetical commas

---

src/js/components/shepherd-element.svelte

We were trying to show arrows when pinned, but this led to pointing to incorrect things. Removing the pinned arrow should fix this.
Fixes #634

Remove pinned arrows

---

src/js/components/shepherd-button.svelte
src/js/components/shepherd-element.svelte
src/js/components/shepherd-footer.svelte
src/js/components/shepherd-header.svelte
src/js/step.js
test/unit/step.spec.js

This change makes it so changes made with `updateStepOptions` actually update the template.  
The `$:` label syntax makes the statement reactive, and executes it on each update of the inputs

Reactively update title and buttons

---

src/js/components/shepherd-element.svelte
src/js/step.js
test/unit/step.spec.js

#655 Allowed the title to be changed reactively, but this caused an issue with the dynamically updated classes on the shepherd-element.  
The issue was that they overrode the classes tether is putting for position and the element disappeared altogether.  
By using the svelte class directive this will no longer be an issue as only the needed classes will be updated, not the whole class list.

Fix dynamic shepherd classes interfering with tether classes

---

src/js/components/shepherd-element.svelte
src/js/step.js
src/js/utils/general.js
src/js/utils/popper-options.js
test/unit/utils/general.spec.js

This fixes the issue with the document scrolling to top before each step is shown. Also, removes extra renders via the forced update in `_step()` method.

🐛 Fix initial scroll to top before scrolling to target

---

src/js/step.js

According to MDN web docs (https://developer.mozilla.org/en-US/docs/Web/API/Element/classList and https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add) Internet Explorer doesn't support multiple arguments for classList.add().
This adds the two classes is separate statements to keep compatibility with IE11.

Single argument on classList.add for IE11 compatibility

---

landing/js/welcome.js
src/js/step.js
src/js/tour.js
test/unit/components/shepherd-modal.spec.js

This cleans up the overlay containers on destroy to stop polluting the DOM further. 
closes #663

🐛 Remove overlay container on destroy

---

src/js/components/shepherd-button.svelte

Make shepherd-button capable of displaying HTML.  Without @html Svelte converts the value into a textNode, which escapes HTML. 
#865

Update shepherd-button.svelte to allow HTML

---

.prettierrc.js
src/js/utils/general.js
test/unit/step.spec.js
test/unit/tour.spec.js

Previously, we were not merging in `defaultStepOptions` modifiers at all because they were overwritten by the step. This adds the same treatment for `defaultStepOptions.popperOptions` as `step.options.popperOptions`. 
This issue is caused by setup being in a weird order. Rather than setting up these options at different times, we should probably fix the `_setOptions` call to do this setup work, so the merging is not clobbering itself.
Closes #919 
Closes #915

Fix defaultStepOptions.popperOptions issues

---

src/js/step.js

This avoids keeping a polluted state around when setting up multiple step options.
Fixes #915

Deep copy defaultStepOptions

---

docs-src/tutorials/04-cookbook.md

Since `document.querySlector` is used, the `document.querySelector('.shepherd-header')` would still give the header of step 1 even if it is executed for step 2. Hence changed it to use step element 'el' instead of document.

cookbook - progress bar code snippet fix  to show in all steps

---

src/js/components/shepherd-element.svelte
src/js/components/shepherd-text.svelte

closes: #837 
mobile:
and desktop:

🐛 Fix centered sizing and add max height defaults for text

---

docs-src/tutorials/04-cookbook.md

closes #525 
This is adding the cookbook item for ideas on how to highlight multiple items in Shepherd, as currently designed.

📝 Add cookbook item for multi item highlighting

---

src/js/components/shepherd-element.svelte

According to the docs, we should be hiding the arrow if you do not define `attachTo.on` so this should fix that issue.
Fixes #978

Require attachTo.on to show arrow

---

src/types/step.d.ts

Update step.d.ts
With accordance to https://github.com/shipshapecode/shepherd/blob/ad5b9b0daa3a2db1a507b70f6f4d6b5620add40d/src/js/step.js#L332 the "this" context is set to the Step

Added the correct this context to StepOption 'when' functions

---

src/js/step.js
src/types/step.d.ts

Hey @rwwagner90 Sorry, I have been some time, I have had family duties and also it seems I am being super dumb so it's really slowing me down.
I have never tried to do advanced things with JSdocs, so I am failing to see how I can nicely add the 'this' context to JSDocs.. I am more a typescript person who has dabbled with JSDocs in the past..
So I have utterly failed to see how to assign the context without making it look like a function argument, so.. I left it as is. (Sorry)
The second thing I have been struggling with is double checking on what `getTarget()` could return..
I was destroying my brain going around in circles over and over going down dead ends and all sorts trying to find where this.target was assigned in `step.js`.. 
And then I finally found `step.target` in `general.js` …

Step Element Target Action

---

.browserslistrc

- Enables transpilation of object property spread
- Required for (old) EdgeHTML 18 compatibility
- Fixes #1023

Add Edge 18 to browserslist

---

src/js/components/shepherd-text.svelte
src/js/step.js
src/js/tour.js
src/js/utils/type-check.js

Use isElement fot svg scrollIntoView support

---

src/types/step.d.ts

Hello,
When trying to use the `react-shepherd` library with TypeScript, I saw that `secondary` property is currently missing in the `StepOptionsButton` interface.

Add secondary property on StepOptionsButton

---

src/types/step.d.ts
src/types/tour.d.ts

Exposes the `id` property of `Step` in TypeScript.
Fix the typing of `Tour.getById()` which can return null if given an `id` that's not in the tour.

add Step.id to typings, fix tour.getById() typing

---

src/types/step.d.ts
src/types/tour.d.ts

This PR adds types for:
* the `options` property of the `Step` class
* the `steps` property of the `Tour` class

Add missing types for Step.options and Tour.steps

---

docs-src/tutorials/02-usage.md

I was searching for a way to call a function for multiple events and found #27 , that discussed a feature like this but ended up being closed in favor of using javascript directly.
I think it's a good idea to add this to the docs, so people can find it more easily in the future.
Thanks @BrianSipple for the solution!

Add multiple events example to docs

---

src/js/components/shepherd-element.svelte

This pull request closes #1076 by adding an additional check on `data-popper-placement` attribute on `document.activeElement` when `shiftKey` is pressed

shift + tab handled

---

src/js/step.js
test/unit/step.spec.js

Fixes #1131 
If a step is added without specifically specifying an element to attach to, there was a default to fallback to **document.body**.
When a step was hidden/destroyed, **this.target** was checked which in the case of a non-attached step, **this.target** was null.
- Added a fallback to **document.body** if **this.target** is falsey when hiding/destroying a step
- Removed condition of **this.target** being truthy for calls to **_updateStepTargetOnHide()** 
- Added unit tests to cover this scenario. Validated that the test failed prior to the fix, and that the test now passes.

Added default fallback for target when step is hidden/destroyed

---

rollup.config.js

There is a small typo in rollup.config.js.
Should read `unminified` rather than `unminifed`.

docs: Fix simple typo, unminifed -> unminified

---

docs-src/tutorials/02-usage.md
src/js/step.js
src/js/tour.js
src/types/tour.d.ts
test/unit/tour.spec.js

Hi! This PR adds a new option to TourOptions: `stepsContainer`, which mimics the behaviour of `modalContainer`. Thanks to this new configuration, it is now possible to specify the render target of step elements, as discussed [here](https://github.com/shipshapecode/shepherd/issues/1175).
Also added missing types, and some tests for `modalContainer` while at it.
Related:
https://github.com/shipshapecode/shepherd/issues/1175
https://github.com/shipshapecode/shepherd/pull/1075 (which is almost the same thing, but my PR is a bit more complete)

Add `stepsContainer` option, allowing users to specify rendering target for step elements

---

src/js/step.js

Hey, this fixes an issue where the `shepherd-target-click-disabled` class is not removed from the highlight target after a step is hidden. While `shepherd-active` and `shepherd-target` classes are correctly removed on step `hide`, the `shepherd-target-click-disabled` is not. `shepherd-target-click-disabled` is only removed when the tour completes.
This problem prevents touring the same element twice, where in one step it's not clickable, and in the other it is. See the repro: https://codesandbox.io/s/practical-ives-9j6u9

Remove `shepherd-target-click-disabled` class on step hide

---

src/js/components/shepherd-modal.svelte
test/unit/components/shepherd-modal.spec.js

properly handle centered modal

---

src/js/tour.js

Call the complete function on the last step 
Fixes https://github.com/shipshapecode/shepherd/issues/1353

Fix issue #1353 : Complete the tour when skipStep is the lastStep

---

docs-src/tutorials/01-install.md

When I was looking through the documentation, I couldn't find how to get proper shepherd styles along with shepherdjs. I found out that, I can download it from jsdeliver in the beginning of my script. So I suggested, that cdn link for styles should be placed near cdn link for shepherdjs in 01-install.md file

I faced a problem while was trying to install shepherdjs

---

docs-src/tutorials/02-usage.md

Please, place this information in documentation starter. its very Important for this type lib.
useModalOverlay: true,

Add `useModalOverlay` to example

---

src/types/evented.d.ts

Make second parameter, `handler`, optional to reflect implementation.
Fixes #1757

Fix type signature for `Evented.off()`

---

docs-src/tutorials/02-usage.md
src/js/components/shepherd-button.svelte
src/types/step.d.ts
test/unit/components/shepherd-button.spec.js

Hey folks 👋
This PR:
- adds dynamic `text` and `label` properties for the `button` component
- avoids duplicate code for the `button` component (`getConfigOption` function)
- updates the `button` unit tests
- updates `StepOptionsButton` interface
- updates `usage` docs with the new info about the `button` component
The common case for dynamic text and label button properties is when `Shepherd` is used with an i18n (internationalization) solution and those fields need to be updated on change of the language settings. That has been already in place for the [main text component](https://github.com/shipshapecode/shepherd/blob/master/src/js/components/shepherd-text.svelte#L10) but was missing for the buttons.

Add dynamic text and label properties for buttons

---

src/js/tour.js
test/unit/tour.spec.js

The skipStep method was incorrectly checking if the next index was equal to the step length. This caused the last step to be skipped if the second to last step had a "showOn" function that returned false.
issue reported here: https://github.com/shipshapecode/shepherd/issues/1814

fixed showOn incorrectly skipping an index

---

docs-src/tutorials/02-usage.md
landing/css/welcome.css
src/js/step.js
src/js/utils/general.js
src/types/step.d.ts
test/cypress/integration/test.acceptance.js
test/unit/step.spec.js
test/unit/utils/general.spec.js

- Remove 
- ```Step.isCentered()```
- Write unit tests to evaluate ```shouldCenterStep```
- Write cypress tests to evaluate ```parseAttachTo``` binding with multiple elements
---
**1. Should we get rid of `Step.isCentered` and is `shouldCenterStep` an appropriate alternative?**
- `Step.isCentered` internally approved for removal
- other methods do not deeply depend on `isCentered`
- including `shouldCenterStep` to maintain the ability to evaluate the resolved attachTo options will not destroy the feature for any users that are currently or will want to use it in the future
- `shouldCenterStep` maintains and improves upon `Step.isCentered`
- Testing written in `general.spec.js` to cover reasonable range of potential forms of resolved attachTo options
- `shouldCenterStep` was modified to …

Implement lazy evaluation of attachTo.element

---

src/js/components/shepherd-modal.svelte

Shepherd modal shows opaque (black) background at load in Chrome (not observed in other browsers), but returns to 50% opacity at scroll
- Isolated to the `.shepherd-modal-overlay-container.shepherd-modal-is-visible` css block
- Removing the transition specifications returns to expected 50% opacity at load
- Looked into handling for css transitions in the more recent versions of chrome
- Reference: [Fixing CSS Transitions in Google Chrome - Ben Gillbanks](https://www.binarymoon.co.uk/2014/02/fixing-css-transitions-in-google-chrome/)
- Add `transform` to css selector to force hardware accelerated transition with value of `0` to have no visual effect other than forcing the hardware transition
Closes #1941

Fix chrome opacity bug

---

src/js/utils/general.js
src/js/utils/popper-options.js
test/cypress/integration/test.acceptance.cy.js
test/unit/utils/general.spec.js

Whenever a Tour's default step options is configured with `scrollTo: { behavior: 'smooth', block: 'center' }` the step's target may not always scroll into the center of the viewport when stepping through the tour. 
An example of this behavior can be seen on [Shepherd's welcome page](https://shepherdjs.dev)
What causes this? Shepherd’s popover receives focus while the smooth scroll to the target is in mid-transition.
The sequence of events when a tour step is first shown:
1. Smooth-scrolling to the target begins transitioning
2. After a brief delay, focus is set on the popover and [by default will also trigger a scroll](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) to the element
3. Smooth-scrolling to the target was interrupted by this shift in focus
- Configure …

Fix for smooth scrolling

---

src/types/step.d.ts

I'd like to create Shepherd tour steps dynamically, with step buttons based on the index of the step. The first step would have only the Next button, steps in the middle would have Back and Next buttons, and the last step would have Back and Done buttons. Here's the code:
```
const tour = new Shepherd.Tour({...});
steps.forEach((step, i) => { // steps is an array of objects with properties text, title, and elementIdentifier
// below I want to have "Shepherd.Step.StepOptionsButton" instead of "any"
const buttons: Shepherd.Step.StepOptionsButton[] = []; 
if (i > 0) {
buttons.push({
text: "Back",
action: tour.back
});
}
if (i < this.modelValue.steps.length - 1) {
buttons.push({
text: "Next",
action: tour.next
});
}
if (i == this.modelValue.steps.length - 1) {
buttons.push({
text: "Done", …
```

Exporting StepOptionsButton type to be able to add tour steps buttons dynamically with type checking

---

src/js/utils/floating-ui.js

warnings occur in Firefox Web dev panel console when some attribute in `Element.style` component are set to `undefined`

Bugfix: prevent to show spurious warnings in dev panel console

---

docs-src/tutorials/04-cookbook.md

Hi. 
I noticed that there is an error in the documentation. Popper is being mentioned when in fact FloatingUI should be mentioned. 
This MR fixes this.

Remove mention to Popper on docs

---

src/js/components/shepherd-element.svelte
test/unit/components/shepherd-element.spec.js

This pull prevents key down event propagation on ESC, KEY_RIGHT, KEY_LEFT keys in Shepherd, when the Shepherd keyboardNavigation is enabled in a shepherd tour.
The reason: our underlying web application, like may others, has a listener for ESC, KEY_RIGHT, KEY_LEFT key press to enable shortcut actions. When the Shepherd "onboarding" tour is played and the user uses keyboardNav, our underlying web application also receives the KEY_RIGHT, KEY_LEFT, and ESC events and also handles them. This causes havoc and confusion with the underlying web application doing things that the user did not intend while they were only trying to navigate the Shepherd tour.

Prevent ESC, KEY_RIGHT, KEY_LEFT propagation when keyboardNav is enabled

---

src/js/components/shepherd-element.svelte

This is a patch for #2399 that stops key ESC, Left-Arrow, and Right-Arrow propagation.
This patch is to also stop the default behavior for those keys when navigation is enabled.

Related to #2399, also stop keydown default behavior when navigation is enabled

---

landing/src/components/Footer.astro

The shepherd website uses `polyfll.io`. The PR replaces `polyfill.io` with `cdnjs.cloudflare.com/polyfill`.
----
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, …

📝 Remove `polyfill.io`

---

landing/src/layouts/MainPage.astro
shepherd.js/src/shepherd.ts
shepherd.js/src/tour.ts
shepherd.js/src/utils/general.ts

We still have the Step and Tour NoOp classes to help with SSR, but we don't really need the types and they were causing issues.

Remove NoOp type usage

---

landing/src/layouts/MainPage.astro
pnpm-lock.yaml
shepherd.js/.eslintignore
shepherd.js/package.json
shepherd.js/rollup.config.mjs
shepherd.js/scripts/postprocess.js
shepherd.js/src/step.ts
shepherd.js/src/tour.ts
shepherd.js/tsconfig.json

closes #2785 
The issues with imports were due to `.svelte` imports in the declarations files and that not resolving correctly (workaround for now but just using `Record`) and the need for two declarations files for both cjs and esm.

🐛 Fixes import issues reported in 2785

---

docs-src/package.json
docs-src/src/content/docs/guides/install.mdx
shepherd.js/package.json
shepherd.js/rollup.config.mjs
test/cypress/dummy/index.html
test/cypress/examples/destroying-elements.html

This goes back to one CSS file and adds it to exports so that folks should be able to import it.

Export CSS and just create one file

---

shepherd.js/src/utils/floating-ui.ts

provides a more edge aligned default with Shepherd.js default styles
before: 
after: 
closes #2315 #2302 #1560

🐛 Add small padding to arrow if edge alignment is used

---

packages/pro-js/package.json
packages/react/package.json
packages/react/src/index.tsx
packages/react/test/index.test.tsx
pnpm-lock.yaml

This removes the extra pro setup in the provider, because with automatic tour init in the pro JS lib these wrappers aren't needed.

➖ React: Remove extra pro specific setup

---

docs-src/src/content/docs/recipes/cookbook.md
landing/src/components/Header.astro
landing/src/pages/index.astro
shepherd.js/src/tour.ts

This branch fixes #2961 by changing the order of assigning the currentStep within a Tour and then fires 'show'. 
Also, this adds a button do that the demo tour doesn't start automatically, it's opt in. (e.g., intro.js and driver.js site style)

🐛 Fix event timing issue and add button for demo start

---

landing/src/pages/pricing.astro

This pull request addresses issue #3014, where the "Purchase" button gets stuck in a "loading" state after a user returns from the payment page without completing the payment.

State Fix for Pricing

---

shepherd.js/src/step.ts
shepherd.js/src/utils/floating-ui.ts

Shepherd is already using `ComputePositionConfig` internally in a few places, but the options object itself is typed as `object`, which isn’t really helpful. Not sure if this is done because of some problem with docs — feel free to close this PR in that case!
*   add correct type to `Step.floatingUIOptions`

Fix options type for `options.floatingUIOptions`

---

docs-src/src/content/docs/guides/usage.md
shepherd.js/src/step.ts
shepherd.js/src/utils/floating-ui.ts
test/unit/tour.spec.js

As discussed in #2583, adding `autoPlacement` is not possible due to `flip` being automatically added by shepherd. This PR re-introduces `auto` placements, which were removed a couple of versions back with migration from popper to floating-ui.
When step `attachTo.on` is set to `auto[-start|end]`, we automatically add [`autoPlacement`](https://floating-ui.com/docs/autoPlacement) to the middlewares and remove `flip`, which isn’t compatible with it.
- add `auto[-start|end]` placement options, which were removed when popper was replaced with floating-ui
https://github.com/shipshapecode/shepherd/blob/76fe594ccdf125c42ceddbaa44e017497d8c441a/src/types/step.d.ts#L232
Let me know if there’s any changes you want me to make 🙏

Add 'auto' as placement option

---

shepherd.js/src/components/shepherd-content.svelte
test/cypress/integration/a11y.cy.js

closes #3071 
This removes the tabindex added by the content div that's not needed for tab trapping in the dialog.

♿ Remove tabindex to reduce tabs for modal trap

---

docs-src/src/content/docs/guides/usage.md
shepherd.js/src/step.ts
shepherd.js/src/utils/floating-ui.ts
test/cypress/integration/test.acceptance.cy.js
test/unit/components/shepherd-element.spec.js

Hi! First time contributer.
We have a >4px border radius on out shepherd-element, and our looking to increase it so the arrow doesn't overlay the border radius:
This PR allows you to configure the arrow padding using something like: `arrow: { padding: 10 }`
This builds and tests pass locally, please let me know if there's anything else you need from me on this PR, or anything I missed!

Allow arrow padding to be configured for a step.
