- bower.json
- dist/css/shepherd-theme-arrows-plain-buttons.css
- dist/css/shepherd-theme-arrows.css
- dist/css/shepherd-theme-dark.css
- dist/css/shepherd-theme-default.css
- dist/css/shepherd-theme-square-dark.css
- dist/css/shepherd-theme-square.css
- package.json
- src/css/shepherd-theme-arrows-plain-buttons.sass
- src/css/shepherd-theme-arrows.sass
- src/css/shepherd-theme-dark.sass
- src/css/shepherd-theme-default.sass
- src/css/shepherd-theme-square-dark.sass
- src/css/shepherd-theme-square.sass
> Use pointer-events: none for arrows

- src/js/shepherd.js
Reverts HubSpot/shepherd#99 See comments there for info
> Revert "Change UTF-8 Character to escaped Unicode"

- gulpfile.js
- Removes mangling exemption for Tether to fix undefined function call
@geoffdaigle @timmfin
> Fixes gulp pipeline

- package.json
- added property with valid link to public repo to package.json
> Add Repo to package.json

- README.md
> RM Hubs Copyright

- docs/welcome/index.html
- package.json
- test/dummy/index.html
- webpack.config.js
- yarn.lock
Closes [#263](https://github.com/shipshapecode/shepherd/issues/263).
> Bundle tippy with the main Shepherd distribution file.

- index.md
> Added documentation for tour.removeStep (fixes #278)

- package.json
- src/js/utils/modal.js
- src/scss/_modal-overlay.scss
> Use vh and vw to ensure modal is always full screen

- src/js/utils/dom.js
> Apply scroll listener to all scroll events

- docs/welcome/css/welcome.css
- docs/welcome/js/welcome.js
- src/js/utils.js
Also, set themes for title arrows.
Fixes #314 
Fixes #339
> Add flipping tippy by default, scrollTo for demo

- src/js/modal.js
- src/js/tour.js
> Add createModalOverlay function

- .browserslistrc
- babel.config.js
- package.json
- yarn.lock
> Add back IE support

- src/js/step.js
- src/scss/_base.scss
- test/cypress/integration/a11y.spec.js
- test/unit/step.spec.js
This is the first little bit of progress toward #198 
I hope to keep chugging along and get some better a11y support going!
> Support close with ESC, focus tooltip on `show`

- src/js/step.js
> Only add keydown listeners once

- babel.config.js
- package.json
- rollup.config.js
- src/js/shepherd.js
- yarn.lock
> Start fixing IE11 support

- babel.config.js
- package.json
- rollup.config.js
- yarn.lock
> Polyfill all `usage` with core-js

- src/js/step.js
- src/js/tour.js
This will allow us to have two running Shepherd instances without collisions
> Add prefix to data attributes

- src/types/evented.d.ts
- src/types/shepherd.d.ts
- src/types/step.d.ts
- src/types/tour.d.ts
"export =" is commonJS dependent
> switched to default export in TS typing

- src/js/tour.jsx
> Return focus after closing the tour

- demo/js/welcome.js
- package.json
- rollup.config.js
- src/js/utils/general.js
- yarn.lock
> Use objectAssignDeep to deeply merge tippyOptions

- demo/js/welcome.js
- src/js/components/shepherd-content/shepherd-text/index.jsx
> Support passing elements for text

- src/js/components/shepherd-modal/index.jsx
- src/js/components/shepherd-modal/styles.js
- src/js/styles/generateStyles.js
- test/cypress/integration/modal.spec.js
> Fade in modal overlay

- demo/index.html
If merged, this PR would resolve the issue where the demo app doesn't have a lang attribute specified on the html element.
> fixing a11y issue by adding lang attribute to html element

- demo/index.html
(accidentally deleted the branch before the PR was considered, sorry!) 
If merged, this PR will add the missing alt and role attributes to the img element. In this case, an empty alt attribute and the role of presentation were added, since the image is decorative.
> adding alt and role to img element

- src/types/shepherd.d.ts
> Move activeTour to namespace

- src/js/utils/bind.js
> Use currentTarget for advanceOn

- src/js/components/shepherd-modal/styles.js
> Tie modal z-index to shepherdElementZIndex

- docs-src/tutorials/02-usage.md
- src/js/components/shepherd-element.svelte
- src/js/step.js
- src/js/tour.js
- src/types/step.d.ts
- test/unit/components/shepherd-element.spec.js
- test/unit/components/shepherd-footer.spec.js
- test/unit/components/shepherd-header.spec.js
- test/unit/components/shepherd-modal.spec.js
- test/unit/components/shepherd-text.spec.js
- test/unit/step.spec.js
> Add arrow option

- package.json
- src/js/components/shepherd-modal.svelte
- src/js/step.js
- src/js/tour.js
- test/.eslintrc.js
- test/cypress/integration/a11y.spec.js
- test/cypress/integration/element-targeting.spec.js
- test/cypress/integration/modal.spec.js
- test/cypress/integration/test.acceptance.js
- test/cypress/support/index.js
- test/cypress/utils/setup-tour.js
- test/unit/components/shepherd-element.spec.js
- test/unit/components/shepherd-header.spec.js
- test/unit/components/shepherd-modal.spec.js
- test/unit/setupTests.js
- test/unit/step.spec.js
- test/unit/tour.spec.js
- test/unit/utils/bind.spec.js
- yarn.lock
Closes #548 
This branch removes the need for body data attributes and tests to ensure tours can be run independently.
> Add tests for multiple tours

- src/js/components/shepherd-text.svelte
- src/js/step.js
- test/unit/step.spec.js
I have implemented the changes discussed in #563
> Implement ability to update step options

- package.json
- src/js/step.js
- test/cypress/integration/destroying-elements.spec.js
- test/examples/destroying-elements.html
> Recreate elements each time on show

- src/js/components/shepherd-modal.svelte
- test/unit/components/shepherd-modal.spec.js
Reverts shipshapecode/shepherd#589
> Revert "Adjust modal opening according to scrollParent"

- docs-src/tutorials/02-usage.md
Sorry for being such a trivial PR, but nonetheless I noticed this while going through the docs.
> Add a missing period in the docs

- src/js/components/shepherd-header.svelte
- src/js/components/shepherd-title.svelte
- src/js/step.js
- src/types/step.d.ts
- test/unit/components/shepherd-title.spec.js
> Allow title to specify callback

- src/types/step.d.ts
Updated the Typescript types to include the `updateStepOptions` method introduced with #581
> Added updateStepOptions to step.d.ts

- src/js/step.js
- src/js/utils/general.js
- src/types/step.d.ts
- test/unit/utils/general.spec.js
> Allow passing tetherOptions

- src/js/components/shepherd-element.svelte
- src/js/step.js
- src/js/utils/cleanup.js
- test/unit/utils/cleanup.spec.js
> Disable pointer events for children with canClickTarget

- src/js/tour.js
- src/types/tour.d.ts
- test/unit/tour.spec.js
> Allow passing index to `addStep`

- src/js/components/shepherd-element.svelte
> Update transitions on shepherd element

- docs-src/tutorials/04-cookbook.md
This adds the reference example for how to create progress information in the tour. Closes #459
> 📝 Add basic example of using API for progress

- .github/workflows/publish-github-pages.yml
- .travis.yml
Remove a step from Travis to work on moving into Github for CI
> 👷‍♂️ Adding CI in GH for pages release

- src/js/tour.js
#861 was merged with tests breaking in CI. This makes them happy again.
> 💚 Fix broken tests for modal destroy

- src/js/components/shepherd-content.svelte
- test/unit/components/shepherd-content.spec.js
> Prevent header from rendering when empty

- docs-src/tutorials/02-usage.md
- src/js/step.js
> Corrections in the docs

- src/js/components/shepherd-element.svelte
> 🐛 Add hiding of arrow when attach not found

- docs-src/tutorials/04-cookbook.md
> Add offset to cookbook

- src/js/components/shepherd-element.svelte
> Fix content being blocked by hidden steps

- package.json
- src/js/step.js
- test/unit/step.spec.js
- test/unit/tour.spec.js
- yarn.lock
> Add deepmerge for deep clone functionality

- src/js/utils/general.js
- src/js/utils/popper-options.js
> Ensure step.el exists before focusing

- .travis.yml
- babel.config.js
- jest.config.js
- package.json
- yarn.lock
> Switch to svelte-jester, test with node 12

- package.json
- yarn.lock
Reverts shipshapecode/shepherd#1499
> Revert "Bump tailwindcss from 1.9.6 to 2.1.4"

- src/js/step.js
Fixes bug discovered in https://github.com/shipshapecode/react-shepherd/issues/585
> 🐛 Add check to remove class if canClickTarget is true

- README.md
> Adds Drupal to the list of Projects Using Shepherd

- landing/css/welcome.css
- test/unit/setupTests.js
- test/unit/step.spec.js
When trying to run the test suite I've run into failures on the main branch. That prevent refactoring work so here is what fixed it for me locally.
> Fix calls to setTimeout in tests

- .eslintrc.js
- .github/workflows/test.yml
- cypress.config.js
- src/js/utils/general.js
- test/unit/components/shepherd-modal.spec.js
- test/unit/step.spec.js
- test/unit/utils/general.spec.js
running `yarn lint:js --fix` and addressing the remaining issues
> chore: make yarn lint:js pass

- docs-src/tutorials/04-cookbook.md
Update for the cookbook directions for the following [issue](https://github.com/shipshapecode/shepherd/issues/1269)
Closes #1269
> update cookbook for issue #1269

- docs-src/tutorials/02-usage.md
- src/js/components/shepherd-modal.svelte
- src/js/step.js
- src/js/utils/overlay-path.js
- src/types/step.d.ts
- test/unit/components/shepherd-modal.spec.js
> feat: add ability to specify corner radii

- docs-src/tutorials/02-usage.md
- docs-src/tutorials/04-cookbook.md
- landing/js/welcome.js
- src/js/step.js
- src/types/step.d.ts
- test/cypress/utils/default-steps.js
> Replace references to popperjs

- landing/js/welcome.js
- src/js/utils/floating-ui.js
- test/unit/step.spec.js
- test/unit/tour.spec.js
> Fix arrow offset, add back flipping behavior

- README.md
Adding an example use case of shepherd to Read Me
It's a plugin for an open source application called Budibase. The plugin allows you to easily create interactive walkthroughs.
> Adding an example use case of shepherd to Read Me

- docs-src/tutorials/02-usage.md
Fixes https://github.com/shipshapecode/shepherd/issues/2357
> Added complete method on usage doc

- docs-src/tutorials/01-install.md
> 🎨 Add note in docs about importing styels

- landing/src/components/GithubButton.astro
- landing/src/layouts/MainPage.astro
- landing/src/lib/github.ts
Adds star count to the github button
> ✨ Add dynamic button with stars count from github

- packages/react/package.json
- shepherd.js/package.json
This should fix the issue where the `dist` was not being generated.
> Add prepack scripts

- shepherd.js/src/step.ts
- shepherd.js/src/tour.ts
> 🐛  Add fix for modal reshow from 2436

- shepherd.js/src/components/shepherd-button.svelte
> 🐛  Add missing required type attribute for button

- README.md
> Update README.md for incorrect URL

- packages/pro-js/package.json
This should help release-plan include the pro dist folder
> 👷 Add prepack script to pro-js

- .github/workflows/publish.yml
See https://github.com/wyvox/action-setup-pnpm?tab=readme-ov-file#node-registry-url
> Update publish.yml to have node-registry-url

- shepherd.js/src/evented.ts
> Fix handler type for Evented.off()

- shepherd.js/src/utils/floating-ui.ts
- test/unit/utils/general.spec.js
This branch changes the merge order to ensure that passed in user options run after the defaults.
> 🐛 Fix issue where passed in custom middleware is overridden

- shepherd.js/src/step.ts
> Fix missing closing block

- landing/package.json
- landing/src/actions/index.ts
- pnpm-lock.yaml
> ⬆ Update Polar SDK and use new API
